import { iconField } from "@mvriu5/payload-icon-picker"
import type { Field, GlobalConfig } from "payload"

const iconColorOptions = [
    { label: "Neutral", value: "neutral" },
    { label: "Brand", value: "brand" },
    { label: "Aqua", value: "aqua" },
    { label: "Blue", value: "blue" },
    { label: "Pink", value: "pink" },
    { label: "Yellow", value: "yellow" },
    { label: "Lime", value: "lime" },
    { label: "Magenta", value: "magenta" },
]

const summaryIconField = (name: string, label: string, defaultValue: string): Field =>
    iconField({
        name,
        label,
        required: true,
        defaultValue,
        placeholder: "Search icons",
        noResultsLabel: "No icons found",
    })

const summaryIconColorField = (name: string, defaultValue: string): Field => ({
    name,
    label: "Icon Color",
    type: "select",
    required: true,
    defaultValue,
    options: iconColorOptions,
})

export const Checkout: GlobalConfig = {
    slug: "checkout",
    access: {
        read: () => true,
        update: ({ req }) => Boolean(req.user),
    },
    fields: [
        {
            name: "title",
            type: "text",
            required: true,
            defaultValue: "Checkout Content",
        },
        {
            name: "navigation",
            type: "group",
            fields: [{ name: "backLabel", type: "text", required: true, localized: true, defaultValue: "Back" }],
        },
        {
            name: "stepper",
            type: "group",
            fields: [
                { name: "configurationLabel", type: "text", required: true, localized: true, defaultValue: "Configuration" },
                { name: "billingAddressLabel", type: "text", required: true, localized: true, defaultValue: "Billing Address" },
                { name: "paymentLabel", type: "text", required: true, localized: true, defaultValue: "Payment" },
                { name: "successLabel", type: "text", required: true, localized: true, defaultValue: "Success" },
            ],
        },
        {
            name: "summary",
            type: "group",
            fields: [
                { name: "eyebrow", type: "text", required: true, localized: true, defaultValue: "Order Summary" },
                { name: "heading", type: "text", required: true, localized: true, defaultValue: "Review your configuration" },
                {
                    name: "description",
                    type: "textarea",
                    required: true,
                    localized: true,
                    defaultValue: "This checkout reflects the subscription shape you configured, including runtime and optional add-ons.",
                },
                { name: "deploymentLabel", type: "text", required: true, localized: true, defaultValue: "Deployment" },
                {
                    name: "deploymentIcons",
                    label: "Deployment Icons",
                    type: "group",
                    fields: [summaryIconField("cloud", "Cloud Icon", "tabler:IconCloud"), summaryIconField("selfHosted", "Self-hosted Icon", "tabler:IconServer")],
                },
                summaryIconColorField("deploymentIconColor", "aqua"),
                { name: "customerTypeLabel", type: "text", required: true, localized: true, defaultValue: "Customer Type" },
                {
                    name: "customerTypeIcons",
                    label: "Customer Type Icons",
                    type: "group",
                    fields: [summaryIconField("b2b", "B2B Icon", "tabler:IconUsers"), summaryIconField("b2c", "B2C Icon", "tabler:IconBuildingStore")],
                },
                summaryIconColorField("customerTypeIconColor", "yellow"),
                { name: "aiTokensLabel", type: "text", required: true, localized: true, defaultValue: "AI Tokens" },
                summaryIconField("aiTokensIcon", "AI Tokens Icon", "tabler:IconBrain"),
                summaryIconColorField("aiTokensIconColor", "magenta"),
                { name: "workflowExecutionsLabel", type: "text", required: true, localized: true, defaultValue: "Workflow Executions" },
                summaryIconField("workflowExecutionsIcon", "Workflow Executions Icon", "tabler:IconBolt"),
                summaryIconColorField("workflowExecutionsIconColor", "brand"),
                { name: "additionalFeaturesLabel", type: "text", required: true, localized: true, defaultValue: "Additional Features" },
                summaryIconField("additionalFeaturesIcon", "Additional Features Icon", "tabler:IconSparkles"),
                summaryIconColorField("additionalFeaturesIconColor", "yellow"),
                {
                    name: "additionalFeaturesDescription",
                    type: "textarea",
                    required: true,
                    localized: true,
                    defaultValue: "Selected add-ons that extend the base subscription.",
                },
                {
                    name: "pricing",
                    type: "group",
                    fields: [
                        { name: "label", type: "text", required: true, localized: true, defaultValue: "Pricing" },
                        {
                            name: "description",
                            type: "textarea",
                            required: true,
                            localized: true,
                            defaultValue: "Monthly breakdown based on your current setup.",
                        },
                        { name: "planLabel", type: "text", required: true, localized: true, defaultValue: "Plan" },
                        { name: "baseLabel", type: "text", required: true, localized: true, defaultValue: "AI Tokens" },
                        { name: "workflowExecutionsLabel", type: "text", required: true, localized: true, defaultValue: "Workflow Executions" },
                        { name: "additionalFeaturesLabel", type: "text", required: true, localized: true, defaultValue: "Additional Features" },
                        { name: "quarterlyDiscountLabel", type: "text", required: true, localized: true, defaultValue: "Quarterly discount" },
                        { name: "yearlyDiscountLabel", type: "text", required: true, localized: true, defaultValue: "Yearly discount" },
                        { name: "discountLabel", type: "text", required: true, localized: true, defaultValue: "Discount" },
                        { name: "discountInputPlaceholder", type: "text", required: true, localized: true, defaultValue: "Discount code" },
                        { name: "discountButtonLabel", type: "text", required: true, localized: true, defaultValue: "Apply" },
                        { name: "discountPromptLabel", type: "text", required: true, localized: true, defaultValue: "Have a discount?" },
                        { name: "discountRemoveLabel", type: "text", required: true, localized: true, defaultValue: "Remove" },
                        { name: "taxLabel", type: "text", required: true, localized: true, defaultValue: "Tax" },
                        { name: "totalLabel", type: "text", required: true, localized: true, defaultValue: "Total" },
                        { name: "perMonthSuffix", type: "text", required: true, localized: true, defaultValue: "/mo" },
                    ],
                },
            ],
        },
        {
            name: "form",
            type: "group",
            fields: [
                { name: "billingHeading", type: "text", required: true, localized: true, defaultValue: "Billing Address" },
                { name: "paymentHeading", type: "text", required: true, localized: true, defaultValue: "Payment Details" },
                { name: "continueLabel", type: "text", required: true, localized: true, defaultValue: "Continue to Payment" },
                { name: "backToBillingLabel", type: "text", required: true, localized: true, defaultValue: "Back to Billing" },
                { name: "payNowLabel", type: "text", required: true, localized: true, defaultValue: "Pay now" },
                { name: "processingLabel", type: "text", required: true, localized: true, defaultValue: "Processing..." },
                { name: "paymentErrorFallback", type: "text", required: true, localized: true, defaultValue: "An unexpected error occurred." },
                { name: "nameLabel", type: "text", required: true, localized: true, defaultValue: "Name" },
                { name: "namePlaceholder", type: "text", required: true, localized: true, defaultValue: "Full name or company name" },
                { name: "emailLabel", type: "text", required: true, localized: true, defaultValue: "Email" },
                { name: "emailPlaceholder", type: "text", required: true, localized: true, defaultValue: "billing@example.com" },
                { name: "phoneLabel", type: "text", required: true, localized: true, defaultValue: "Phone" },
                { name: "phonePlaceholder", type: "text", required: true, localized: true, defaultValue: "Optional" },
                { name: "line1Label", type: "text", required: true, localized: true, defaultValue: "Address" },
                { name: "line1Placeholder", type: "text", required: true, localized: true, defaultValue: "Street and house number" },
                { name: "line2Label", type: "text", required: true, localized: true, defaultValue: "Address line 2" },
                { name: "line2Placeholder", type: "text", required: true, localized: true, defaultValue: "Optional" },
                { name: "cityLabel", type: "text", required: true, localized: true, defaultValue: "City" },
                { name: "stateLabel", type: "text", required: true, localized: true, defaultValue: "State" },
                { name: "statePlaceholder", type: "text", required: true, localized: true, defaultValue: "Optional" },
                { name: "postalCodeLabel", type: "text", required: true, localized: true, defaultValue: "Postal code" },
                { name: "countryLabel", type: "text", required: true, localized: true, defaultValue: "Country" },
                { name: "countryPlaceholder", type: "text", required: true, localized: true, defaultValue: "Select a country" },
                { name: "countryEmptyLabel", type: "text", required: true, localized: true, defaultValue: "No country found." },
                { name: "taxIdTypeLabel", type: "text", required: true, localized: true, defaultValue: "Tax ID type" },
                { name: "taxIdTypePlaceholder", type: "text", required: true, localized: true, defaultValue: "eu_vat" },
                { name: "taxIdValueLabel", type: "text", required: true, localized: true, defaultValue: "Tax ID" },
                { name: "taxIdValuePlaceholder", type: "text", required: true, localized: true, defaultValue: "DE123456789" },
            ],
        },
        {
            name: "success",
            type: "group",
            fields: [
                { name: "heading", type: "text", required: true, localized: true, defaultValue: "Payment submitted" },
                {
                    name: "description",
                    type: "textarea",
                    required: true,
                    localized: true,
                    defaultValue: "Stripe has received your payment confirmation. You can close this page or return to the site.",
                },
                { name: "backToHomepageLabel", type: "text", required: true, localized: true, defaultValue: "Return to homepage" },
            ],
        },
    ],
}
