"use client"

import type { StripeCheckoutElementsSdkOptions } from "@stripe/stripe-js"
export const STRIPE_APPEARANCE_VERSION = "pictor-7"
export const stripeAppearance = {
    theme: "night",
    labels: "above",
    variables: {
        colorPrimary: "#72f896",
        colorBackground: "#201e2c",
        colorText: "#ffffff",
        colorTextSecondary: "rgba(255, 255, 255, 0.5)",
        colorTextPlaceholder: "rgba(255, 255, 255, 0.35)",
        colorDanger: "#ef5b68",
        tabIconColor: "rgba(255, 255, 255, 0.7)",
        tabIconHoverColor: "#ffffff",
        tabIconSelectedColor: "#ffffff",
        tabIconMoreColor: "rgba(255, 255, 255, 0.7)",
        tabIconMoreHoverColor: "#ffffff",
        fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
        fontSizeBase: "13px",
        fontWeightNormal: "400",
        fontWeightMedium: "400",
        spacingUnit: "4px",
        gridRowSpacing: "16px",
        borderRadius: "16px",
        focusBoxShadow: "none",
        focusOutline: "none",
        inputBoxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.1)",
        inputFocusBoxShadow: "none",
        inputFocusColorBorder: "transparent",
        labelColorText: "rgba(255, 255, 255, 0.5)",
        labelFontSize: "11px",
        labelFontWeight: "400",
        labelSpacing: "7px",
    },
    rules: {
        ".Input": {
            backgroundColor: "#272532",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.1)",
            padding: "11px",
            letterSpacing: "-0.5px",
        },
        ".Input:hover": {
            backgroundColor: "rgba(191, 191, 191, 0.15)",
        },
        ".Input:focus": {
            backgroundColor: "rgba(191, 191, 191, 0.15)",
            border: "none",
            boxShadow: "none",
            outline: "none",
        },
        ".Input--invalid": {
            backgroundColor: "#1c0516",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(217, 4, 41, 0.1)",
        },
        ".Dropdown": {
            backgroundColor: "#191825",
            border: "none",
            borderRadius: "16px",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.1), 0 12px 32px rgba(0, 0, 0, 0.35)",
        },
        ".DropdownItem": {
            backgroundColor: "transparent",
            borderRadius: "10px",
            color: "rgba(255, 255, 255, 0.75)",
            fontSize: "13px",
            margin: "4px",
            padding: "10px 12px",
        },
        ".DropdownItem--highlight": {
            backgroundColor: "#201e2c",
            color: "#ffffff",
        },
        ".DropdownItem:active": {
            backgroundColor: "rgba(191, 191, 191, 0.2)",
            color: "#ffffff",
        },
        ".DropdownItem:focus": {
            backgroundColor: "#201e2c",
            color: "#ffffff",
            outline: "none",
        },
        ".Label": {
            color: "rgba(255, 255, 255, 0.5)",
            fontSize: "11px",
            fontWeight: "400",
            letterSpacing: "-0.5px",
            textTransform: "uppercase",
        },
        ".Block": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem--selected": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem:focus": {
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem:hover": {
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem--highlight": {
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem:active": {
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem--selected:hover": {
            backgroundColor: "#191825",
            border: "none",
            borderColor: "transparent",
            borderWidth: "0px",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
            outlineOffset: "0px",
        },
        ".PickerItem--selected:focus": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem--selected:active": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
        },
        ".PickerItem--highlight:hover": {
            backgroundColor: "#191825",
            border: "none",
            borderColor: "transparent",
            borderWidth: "0px",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
            outlineOffset: "0px",
        },
        ".PickerItem--highlight:focus": {
            backgroundColor: "#191825",
            border: "none",
            borderColor: "transparent",
            borderWidth: "0px",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
            outlineOffset: "0px",
        },
        ".PickerItem--highlight:active": {
            backgroundColor: "#191825",
            border: "none",
            borderColor: "transparent",
            borderWidth: "0px",
            boxShadow: "inset 0 1px 1px rgba(191, 191, 191, 0.1)",
            outline: "none",
            outlineOffset: "0px",
        },
        ".Tab": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.1)",
            color: "rgba(255, 255, 255, 0.7)",
            padding: "12px 14px",
        },
        ".Tab:hover": {
            backgroundColor: "#201e2c",
            color: "#ffffff",
        },
        ".Tab--selected": {
            backgroundColor: "#302e3b",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.12)",
            color: "#ffffff",
        },
        ".Tab--selected:hover": {
            backgroundColor: "#302e3b",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.12)",
            color: "#ffffff",
        },
        ".Tab:focus": {
            backgroundColor: "#302e3b",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.12)",
            outline: "none",
        },
        ".AccordionItem": {
            backgroundColor: "#191825",
            border: "none",
            boxShadow: "inset 0 1px 1px rgba(255, 255, 255, 0.1)",
        },
        ".AccordionItem:hover": {
            backgroundColor: "#201e2c",
        },
        ".AccordionItem--selected": {
            backgroundColor: "#201e2c",
            border: "none",
            boxShadow: "none",
        },
        ".AccordionItem:focus-visible": {
            backgroundColor: "#2b2938",
            boxShadow: "none",
            outline: "none",
        },
    },
} satisfies NonNullable<NonNullable<StripeCheckoutElementsSdkOptions["elementsOptions"]>["appearance"]>
