import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_install_language" AS ENUM('bsl', 'sdbl', 'abap', 'actionscript-3', 'ada', 'angular-html', 'angular-ts', 'apache', 'apex', 'apl', 'applescript', 'ara', 'asciidoc', 'razor', 'asm', 'astro', 'awk', 'ballerina', 'bat', 'beancount', 'berry', 'bibtex', 'bicep', 'bird2', 'blade', 'c', 'csharp', 'cpp', 'c3', 'cadence', 'cairo', 'clarity', 'clojure', 'soy', 'cmake', 'cobol', 'codeowners', 'codeql', 'coffee', 'common-lisp', 'coq', 'crystal', 'css', 'csv', 'cue', 'cypher', 'd', 'dart', 'dax', 'desktop', 'diff', 'docker', 'dotenv', 'dream-maker', 'edge', 'elixir', 'elm', 'emacs-lisp', 'erb', 'erlang', 'fsharp', 'fennel', 'fish', 'fluent', 'fortran-fixed-form', 'fortran-free-form', 'gdresource', 'gdscript', 'gdshader', 'genie', 'po', 'gherkin', 'git-commit', 'git-rebase', 'gleam', 'glimmer-js', 'glimmer-ts', 'glsl', 'gn', 'gnuplot', 'go', 'graphql', 'groovy', 'hack', 'handlebars', 'hcl', 'haskell', 'haxe', 'hjson', 'hlsl', 'html', 'html-derivative', 'http', 'hurl', 'hxml', 'hy', 'imba', 'ini', 'java', 'javascript', 'jinja', 'jison', 'json', 'jsonl', 'jsonc', 'json5', 'jsonnet', 'jssm', 'jsx', 'julia', 'just', 'kdl', 'kotlin', 'kusto', 'latex', 'lean', 'less', 'liquid', 'llvm', 'log', 'logo', 'lua', 'luau', 'make', 'markdown', 'marko', 'matlab', 'mdc', 'mdx', 'mermaid', 'mipsasm', 'mojo', 'moonbit', 'move', 'narrat', 'nextflow', 'nextflow-groovy', 'nginx', 'nim', 'nix', 'nushell', 'objective-c', 'objective-cpp', 'ocaml', 'odin', 'openscad', 'pascal', 'perl', 'php', 'pkl', 'plsql', 'polar', 'postcss', 'powerquery', 'powershell', 'prisma', 'prolog', 'proto', 'pug', 'puppet', 'purescript', 'python', 'qml', 'qmldir', 'qss', 'r', 'racket', 'raku', 'regexp', 'rel', 'rst', 'riscv', 'ron', 'rosmsg', 'ruby', 'haml', 'rust', 'sas', 'sass', 'scala', 'scheme', 'scss', 'shaderlab', 'shellscript', 'shellsession', 'smalltalk', 'solidity', 'sparql', 'splunk', 'sql', 'ssh-config', 'stata', 'stylus', 'surrealql', 'svelte', 'swift', 'systemd', 'system-verilog', 'talonscript', 'tasl', 'tcl', 'templ', 'terraform', 'tex', 'toml', 'tsv', 'tsx', 'turtle', 'twig', 'typescript', 'ts-tags', 'typespec', 'typst', 'v', 'vala', 'verilog', 'vhdl', 'viml', 'vb', 'vue', 'vue-html', 'vue-vine', 'vyper', 'wasm', 'wit', 'wenyan', 'wgsl', 'wikitext', 'reg', 'wolfram', 'xml', 'xsl', 'yaml', 'zenscript', 'zig');
  ALTER TABLE "pages_blocks_install" ADD COLUMN "language" "enum_pages_blocks_install_language";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_install" DROP COLUMN "language";
  DROP TYPE "public"."enum_pages_blocks_install_language";`)
}
