import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "subscription_config_feature_overview" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "subscription_config_feature_overview_locales" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "subscription_config_feature_overview_locales" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "subscription_config_workflow_calculator_business_types" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "subscription_config_workflow_calculator_business_types" ALTER COLUMN "conversion_rate" DROP NOT NULL;
  ALTER TABLE "subscription_config_workflow_calculator_business_types_locales" ALTER COLUMN "conversion_unit" DROP NOT NULL;
  ALTER TABLE "subscription_config_additional_features" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "subscription_config_additional_features" ALTER COLUMN "price" DROP NOT NULL;
  ALTER TABLE "subscription_config_additional_features_locales" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "subscription_config_additional_features_locales" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_self_hosted_icon" SET DEFAULT 'server';
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_self_hosted_icon" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_self_hosted_color" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_cloud_icon" SET DEFAULT 'cloud';
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_cloud_icon" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_cloud_color" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2b_icon" SET DEFAULT 'briefcase-2';
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2b_icon" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2b_color" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2c_icon" SET DEFAULT 'building-store';
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2c_icon" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2c_color" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_pro_icon" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_pro_color" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_team_icon" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_team_color" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_executions_min" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_executions_max" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_executions_step" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_execution_price_factor" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_tokens_min" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_tokens_max" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_tokens_step" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_token_price_factor" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "contact_sales_href" SET DEFAULT '/contact';
  ALTER TABLE "subscription_config" ALTER COLUMN "contact_sales_href" DROP NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscribe_base_url" SET DEFAULT '';
  ALTER TABLE "subscription_config" ALTER COLUMN "subscribe_base_url" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_heading" SET DEFAULT 'Configure your setup before you talk pricing.';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_heading" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_description" SET DEFAULT 'Pick your operating model, customer shape, and usage pattern. The right-hand side updates into a purchase-ready configuration flow instead of a generic pricing table.';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "options_panel_heading" SET DEFAULT 'Build the subscription shape';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "options_panel_heading" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_label" SET DEFAULT 'Deployment';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_title" SET DEFAULT 'Self-hosted';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_description" SET DEFAULT 'Deploy on your own infrastructure with full operational control.';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_title" SET DEFAULT 'Cloud';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_description" SET DEFAULT 'Use managed infrastructure with selectable runtime consumption.';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_label" SET DEFAULT 'Customer Type';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_title" SET DEFAULT 'B2B';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_description" SET DEFAULT 'Organization purchase flow with tailored commercial handling.';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_title" SET DEFAULT 'B2C';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_description" SET DEFAULT 'Standardized subscription flow with directly selectable plans.';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_pro_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_pro_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_team_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_team_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_title" SET DEFAULT 'Workflow Executions';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_description" SET DEFAULT 'How many workflow executions do you expect per month?';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_min_label" SET DEFAULT '200 exec';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_min_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_max_label" SET DEFAULT '10,000 exec';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_max_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_center_suffix" SET DEFAULT 'exec';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_center_suffix" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_title" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_description" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_min_label" SET DEFAULT '100K tokens';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_min_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_max_label" SET DEFAULT '10M tokens';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_max_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_center_suffix" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_prompt" SET DEFAULT 'Need more?';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_prompt" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_label" SET DEFAULT 'Contact sales';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscribe_label" SET DEFAULT 'Buy now';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscribe_label" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_heading" SET DEFAULT 'Price';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_heading" DROP NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_caption" SET DEFAULT 'per month';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_caption" DROP NOT NULL;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "subscription_config_feature_overview" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "subscription_config_feature_overview_locales" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "subscription_config_feature_overview_locales" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "subscription_config_workflow_calculator_business_types" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "subscription_config_workflow_calculator_business_types" ALTER COLUMN "conversion_rate" SET NOT NULL;
  ALTER TABLE "subscription_config_workflow_calculator_business_types_locales" ALTER COLUMN "conversion_unit" SET NOT NULL;
  ALTER TABLE "subscription_config_additional_features" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "subscription_config_additional_features" ALTER COLUMN "price" SET NOT NULL;
  ALTER TABLE "subscription_config_additional_features_locales" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "subscription_config_additional_features_locales" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_self_hosted_icon" DROP DEFAULT;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_self_hosted_icon" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_self_hosted_color" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_cloud_icon" DROP DEFAULT;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_cloud_icon" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "deployment_cloud_color" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2b_icon" DROP DEFAULT;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2b_icon" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2b_color" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2c_icon" DROP DEFAULT;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2c_icon" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "customer_type_b2c_color" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_pro_icon" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_pro_color" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_team_icon" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscription_tier_team_color" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_executions_min" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_executions_max" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_executions_step" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "workflow_execution_price_factor" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_tokens_min" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_tokens_max" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_tokens_step" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "ai_token_price_factor" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "contact_sales_href" DROP DEFAULT;
  ALTER TABLE "subscription_config" ALTER COLUMN "contact_sales_href" SET NOT NULL;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscribe_base_url" DROP DEFAULT;
  ALTER TABLE "subscription_config" ALTER COLUMN "subscribe_base_url" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_heading" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_heading" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_description" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "page_intro_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "options_panel_heading" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "options_panel_heading" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_label" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_title" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_description" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_self_hosted_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_title" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_description" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "deployment_cloud_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_label" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_title" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_description" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2b_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_title" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_description" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "customer_type_b2c_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_pro_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_pro_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_team_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscription_tier_team_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_title" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_description" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_min_label" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_min_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_max_label" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_max_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_center_suffix" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "workflow_executions_center_suffix" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_title" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_description" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_min_label" SET DEFAULT '100k tokens';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_min_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_max_label" SET DEFAULT '10m tokens';
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_max_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "ai_tokens_center_suffix" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_prompt" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_prompt" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_label" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "contact_sales_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscribe_label" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "subscribe_label" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_heading" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_heading" SET NOT NULL;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_caption" DROP DEFAULT;
  ALTER TABLE "subscription_config_locales" ALTER COLUMN "price_caption" SET NOT NULL;`)
}
