import type { Block } from "payload"

export const JobsBlock: Block = {
  slug: "jobs",
  labels: {
    singular: "Jobs",
    plural: "Jobs Blocks",
  },
  fields: [
    {
      name: "heading",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Join Our Team",
    },
    {
      name: "searchPlaceholder",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Search jobs",
    },
    {
      name: "allLocationsLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "All locations",
    },
    {
      name: "allJobTypesLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "All job types",
    },
    {
      name: "allCategoriesLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "All categories",
    },
    {
      name: "noJobsFoundLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "No jobs found for your filter.",
    },
    {
      name: "applicationHeading",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Apply now",
    },
    {
      name: "applicationNameLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Name",
    },
    {
      name: "applicationNamePlaceholder",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Your name",
    },
    {
      name: "applicationEmailLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Email",
    },
    {
      name: "applicationEmailPlaceholder",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "you@example.com",
    },
    {
      name: "applicationMessageLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Message",
    },
    {
      name: "applicationMessagePlaceholder",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Tell us a bit about yourself...",
    },
    {
      name: "applicationSubmitLabel",
      type: "text",
      required: true,
      localized: true,
      defaultValue: "Send application",
    },
  ],
}
