/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    features: Feature;
    actions: Action;
    jobs: Job;
    blog: Blog;
    'team-members': TeamMember;
    exports: Export;
    imports: Import;
    'payload-ai-auditlog': PayloadAiAuditlog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    actions: ActionsSelect<false> | ActionsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-ai-auditlog': PayloadAiAuditlogSelect<false> | PayloadAiAuditlogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    navigation: Navigation;
    footer: Footer;
    'cookie-banner': CookieBanner;
    subscriptionConfig: SubscriptionConfig;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'cookie-banner': CookieBannerSelect<false> | CookieBannerSelect<true>;
    subscriptionConfig: SubscriptionConfigSelect<false> | SubscriptionConfigSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  image?: (number | null) | Media;
  aiProvider?: ('claude' | 'google' | 'mistral' | 'openai' | 'openrouter') | null;
  /**
   * Optional. If empty, the plugin uses the provider API key from environment variables.
   */
  aiApiKey?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  href?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug:
    | 'main'
    | 'jobs'
    | 'blog'
    | 'features'
    | 'about-us'
    | 'legal-notice'
    | 'privacy'
    | 'terms'
    | 'open-source-no-code-automation'
    | 'contact'
    | 'actions'
    | 'community-edition'
    | 'enterprise-edition'
    | 'subscription';
  layout?:
    | (
        | {
            badge?: string | null;
            badge_link?: string | null;
            heading: string;
            centered?: boolean | null;
            image?: (number | null) | Media;
            grainientColors?: {
              color1?: string | null;
              color2?: string | null;
              color3?: string | null;
              backgroundColor?: string | null;
            };
            texts?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            buttons?:
              | {
                  label: string;
                  url: string;
                  variant?: ('none' | 'normal' | 'outlined' | 'filled') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            sectionHeading?: string | null;
            sectionLayout: 'center' | 'left';
            sectionDescription?: string | null;
            sectionLinkButton?: {
              label?: string | null;
              url?: string | null;
            };
            variant: 'feature' | 'runtime';
            id?: string | null;
            blockName?: string | null;
            blockType: 'bento';
          }
        | {
            sectionHeading?: string | null;
            sectionLayout: 'center' | 'left';
            sectionDescription?: string | null;
            sectionLinkButton?: {
              label?: string | null;
              url?: string | null;
            };
            cards: {
              label: string;
              title: string;
              description: string;
              image?: (number | null) | Media;
              bulletPoints?: string[] | null;
              link?: {
                label?: string | null;
                url?: string | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'offsetCards';
          }
        | {
            heading: string;
            subheading: string;
            label?: string | null;
            /**
             * Syntax highlighting language. Defaults to Bash when left empty.
             */
            language?:
              | (
                  | 'bsl'
                  | 'sdbl'
                  | 'abap'
                  | 'actionscript-3'
                  | 'ada'
                  | 'angular-html'
                  | 'angular-ts'
                  | 'apache'
                  | 'apex'
                  | 'apl'
                  | 'applescript'
                  | 'ara'
                  | 'asciidoc'
                  | 'razor'
                  | 'asm'
                  | 'astro'
                  | 'awk'
                  | 'ballerina'
                  | 'bat'
                  | 'beancount'
                  | 'berry'
                  | 'bibtex'
                  | 'bicep'
                  | 'bird2'
                  | 'blade'
                  | 'c'
                  | 'csharp'
                  | 'cpp'
                  | 'c3'
                  | 'cadence'
                  | 'cairo'
                  | 'clarity'
                  | 'clojure'
                  | 'soy'
                  | 'cmake'
                  | 'cobol'
                  | 'codeowners'
                  | 'codeql'
                  | 'coffee'
                  | 'common-lisp'
                  | 'coq'
                  | 'crystal'
                  | 'css'
                  | 'csv'
                  | 'cue'
                  | 'cypher'
                  | 'd'
                  | 'dart'
                  | 'dax'
                  | 'desktop'
                  | 'diff'
                  | 'docker'
                  | 'dotenv'
                  | 'dream-maker'
                  | 'edge'
                  | 'elixir'
                  | 'elm'
                  | 'emacs-lisp'
                  | 'erb'
                  | 'erlang'
                  | 'fsharp'
                  | 'fennel'
                  | 'fish'
                  | 'fluent'
                  | 'fortran-fixed-form'
                  | 'fortran-free-form'
                  | 'gdresource'
                  | 'gdscript'
                  | 'gdshader'
                  | 'genie'
                  | 'po'
                  | 'gherkin'
                  | 'git-commit'
                  | 'git-rebase'
                  | 'gleam'
                  | 'glimmer-js'
                  | 'glimmer-ts'
                  | 'glsl'
                  | 'gn'
                  | 'gnuplot'
                  | 'go'
                  | 'graphql'
                  | 'groovy'
                  | 'hack'
                  | 'handlebars'
                  | 'hcl'
                  | 'haskell'
                  | 'haxe'
                  | 'hjson'
                  | 'hlsl'
                  | 'html'
                  | 'html-derivative'
                  | 'http'
                  | 'hurl'
                  | 'hxml'
                  | 'hy'
                  | 'imba'
                  | 'ini'
                  | 'java'
                  | 'javascript'
                  | 'jinja'
                  | 'jison'
                  | 'json'
                  | 'jsonl'
                  | 'jsonc'
                  | 'json5'
                  | 'jsonnet'
                  | 'jssm'
                  | 'jsx'
                  | 'julia'
                  | 'just'
                  | 'kdl'
                  | 'kotlin'
                  | 'kusto'
                  | 'latex'
                  | 'lean'
                  | 'less'
                  | 'liquid'
                  | 'llvm'
                  | 'log'
                  | 'logo'
                  | 'lua'
                  | 'luau'
                  | 'make'
                  | 'markdown'
                  | 'marko'
                  | 'matlab'
                  | 'mdc'
                  | 'mdx'
                  | 'mermaid'
                  | 'mipsasm'
                  | 'mojo'
                  | 'moonbit'
                  | 'move'
                  | 'narrat'
                  | 'nextflow'
                  | 'nextflow-groovy'
                  | 'nginx'
                  | 'nim'
                  | 'nix'
                  | 'nushell'
                  | 'objective-c'
                  | 'objective-cpp'
                  | 'ocaml'
                  | 'odin'
                  | 'openscad'
                  | 'pascal'
                  | 'perl'
                  | 'php'
                  | 'pkl'
                  | 'plsql'
                  | 'polar'
                  | 'postcss'
                  | 'powerquery'
                  | 'powershell'
                  | 'prisma'
                  | 'prolog'
                  | 'proto'
                  | 'pug'
                  | 'puppet'
                  | 'purescript'
                  | 'python'
                  | 'qml'
                  | 'qmldir'
                  | 'qss'
                  | 'r'
                  | 'racket'
                  | 'raku'
                  | 'regexp'
                  | 'rel'
                  | 'rst'
                  | 'riscv'
                  | 'ron'
                  | 'rosmsg'
                  | 'ruby'
                  | 'haml'
                  | 'rust'
                  | 'sas'
                  | 'sass'
                  | 'scala'
                  | 'scheme'
                  | 'scss'
                  | 'shaderlab'
                  | 'shellscript'
                  | 'shellsession'
                  | 'smalltalk'
                  | 'solidity'
                  | 'sparql'
                  | 'splunk'
                  | 'sql'
                  | 'ssh-config'
                  | 'stata'
                  | 'stylus'
                  | 'surrealql'
                  | 'svelte'
                  | 'swift'
                  | 'systemd'
                  | 'system-verilog'
                  | 'talonscript'
                  | 'tasl'
                  | 'tcl'
                  | 'templ'
                  | 'terraform'
                  | 'tex'
                  | 'toml'
                  | 'tsv'
                  | 'tsx'
                  | 'turtle'
                  | 'twig'
                  | 'typescript'
                  | 'ts-tags'
                  | 'typespec'
                  | 'typst'
                  | 'v'
                  | 'vala'
                  | 'verilog'
                  | 'vhdl'
                  | 'viml'
                  | 'vb'
                  | 'vue'
                  | 'vue-html'
                  | 'vue-vine'
                  | 'vyper'
                  | 'wasm'
                  | 'wit'
                  | 'wenyan'
                  | 'wgsl'
                  | 'wikitext'
                  | 'reg'
                  | 'wolfram'
                  | 'xml'
                  | 'xsl'
                  | 'yaml'
                  | 'zenscript'
                  | 'zig'
                )
              | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'install';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            cards: {
              title: string;
              description: string;
              image?: (number | null) | Media;
              link?: {
                label?: string | null;
                url?: string | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'swipeCards';
          }
        | {
            description: string;
            logos?:
              | {
                  logo: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brand';
          }
        | {
            sectionHeading?: string | null;
            sectionLayout: 'center' | 'left';
            sectionDescription?: string | null;
            sectionLinkButton?: {
              label?: string | null;
              url?: string | null;
            };
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            subheading: string;
            ctaLink: {
              label: string;
              url: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading: string;
            searchPlaceholder: string;
            allLocationsLabel: string;
            allJobTypesLabel: string;
            allCategoriesLabel: string;
            noJobsFoundLabel: string;
            applicationHeading: string;
            applicationNameLabel: string;
            applicationNamePlaceholder: string;
            applicationEmailLabel: string;
            applicationEmailPlaceholder: string;
            applicationMessageLabel: string;
            applicationMessagePlaceholder: string;
            applicationSubmitLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'jobs';
          }
        | {
            viewOtherBlogsLabel: string;
            noPostsLabel: string;
            loadMoreLabel: string;
            loadingLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog';
          }
        | {
            heading: string;
            description: string;
            searchPlaceholder: string;
            noActionsFoundLabel: string;
            referencesLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'actions';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown';
          }
        | {
            heading: string;
            description: string;
            nameLabel: string;
            namePlaceholder: string;
            emailLabel: string;
            emailPlaceholder: string;
            messageLabel: string;
            messagePlaceholder: string;
            submitLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            sectionHeading?: string | null;
            sectionLayout: 'center' | 'left';
            sectionDescription?: string | null;
            sectionLinkButton?: {
              label?: string | null;
              url?: string | null;
            };
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardRow';
          }
        | {
            sectionHeading?: string | null;
            sectionLayout: 'center' | 'left';
            sectionDescription?: string | null;
            sectionLinkButton?: {
              label?: string | null;
              url?: string | null;
            };
            items: {
              time: string;
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'roadmap';
          }
        | {
            items: {
              title: string;
              description?: string | null;
              showImageBorder?: boolean | null;
              sectionLayout:
                | 'imageRight'
                | 'imageLeft'
                | 'imageFullscreen'
                | 'imageRightFullscreen'
                | 'imageLeftFullscreen';
              gradient?: ('blue' | 'yellow' | 'pink' | 'aqua' | 'brand' | 'neutral') | null;
              gradientDirection?: ('topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight') | null;
              bulletPoints?: string[] | null;
              image?: (number | null) | Media;
              link?: {
                label?: string | null;
                url?: string | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'scrollCards';
          }
        | {
            title: string;
            description?: string | null;
            showImageBorder?: boolean | null;
            sectionLayout:
              | 'imageRight'
              | 'imageLeft'
              | 'imageFullscreen'
              | 'imageRightFullscreen'
              | 'imageLeftFullscreen';
            gradient?: ('blue' | 'yellow' | 'pink' | 'aqua' | 'brand' | 'neutral') | null;
            gradientDirection?: ('topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight') | null;
            bulletPoints?: string[] | null;
            image?: (number | null) | Media;
            link?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'standaloneCard';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  slug:
    | 'projects'
    | 'role-system'
    | 'member-management'
    | 'organizations'
    | 'suggestion-menu'
    | 'nodes'
    | 'runtime-types'
    | 'action-list';
  title: string;
  description?: string | null;
  link?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actions".
 */
export interface Action {
  id: number;
  title: string;
  /**
   * URL slug for the action subpage, e.g. 'slack-sync'.
   */
  slug: string;
  shortDescription?: string | null;
  description?: string | null;
  icon?: (number | null) | Media;
  trigger?: (number | null) | Media;
  functiondefinitions?: (number | null) | Media;
  tags?: string[] | null;
  documentation?: {
    label?: string | null;
    url?: string | null;
  };
  references?: (number | Action)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  slug: string;
  category: 'engineering' | 'marketing' | 'design' | 'product' | 'sales' | 'operations';
  type: 'full-time' | 'part-time' | 'contract' | 'internship' | 'working-student' | 'freelance';
  location: 'remote' | 'hybrid' | 'leipzig' | 'solingen';
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional manual sort order. Lower values appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  isPinned?: boolean | null;
  author: number | TeamMember;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  heroImage?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  image?: (number | null) | Media;
  shortDescription?: string | null;
  about?: string | null;
  role?: string | null;
  joinedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'en' | 'de') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-ai-auditlog".
 */
export interface PayloadAiAuditlog {
  id: number;
  title: string;
  action: 'create' | 'update' | 'delete' | 'updateGlobal';
  targetType: 'collection' | 'global';
  collection?: string | null;
  slug?: string | null;
  documentID?: string | null;
  targetURL?: string | null;
  additions?: number | null;
  removals?: number | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  proposal?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  prompt?: string | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
  aiResponse?: string | null;
  userID?: string | null;
  userLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'actions';
        value: number | Action;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'payload-ai-auditlog';
        value: number | PayloadAiAuditlog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  aiProvider?: T;
  aiApiKey?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              badge_link?: T;
              heading?: T;
              centered?: T;
              image?: T;
              grainientColors?:
                | T
                | {
                    color1?: T;
                    color2?: T;
                    color3?: T;
                    backgroundColor?: T;
                  };
              texts?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bento?:
          | T
          | {
              sectionHeading?: T;
              sectionLayout?: T;
              sectionDescription?: T;
              sectionLinkButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        offsetCards?:
          | T
          | {
              sectionHeading?: T;
              sectionLayout?: T;
              sectionDescription?: T;
              sectionLinkButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              cards?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    bulletPoints?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        install?:
          | T
          | {
              heading?: T;
              subheading?: T;
              label?: T;
              language?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        swipeCards?:
          | T
          | {
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        brand?:
          | T
          | {
              description?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionHeading?: T;
              sectionLayout?: T;
              sectionDescription?: T;
              sectionLinkButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        jobs?:
          | T
          | {
              heading?: T;
              searchPlaceholder?: T;
              allLocationsLabel?: T;
              allJobTypesLabel?: T;
              allCategoriesLabel?: T;
              noJobsFoundLabel?: T;
              applicationHeading?: T;
              applicationNameLabel?: T;
              applicationNamePlaceholder?: T;
              applicationEmailLabel?: T;
              applicationEmailPlaceholder?: T;
              applicationMessageLabel?: T;
              applicationMessagePlaceholder?: T;
              applicationSubmitLabel?: T;
              id?: T;
              blockName?: T;
            };
        blog?:
          | T
          | {
              viewOtherBlogsLabel?: T;
              noPostsLabel?: T;
              loadMoreLabel?: T;
              loadingLabel?: T;
              id?: T;
              blockName?: T;
            };
        actions?:
          | T
          | {
              heading?: T;
              description?: T;
              searchPlaceholder?: T;
              noActionsFoundLabel?: T;
              referencesLabel?: T;
              id?: T;
              blockName?: T;
            };
        markdown?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              heading?: T;
              description?: T;
              nameLabel?: T;
              namePlaceholder?: T;
              emailLabel?: T;
              emailPlaceholder?: T;
              messageLabel?: T;
              messagePlaceholder?: T;
              submitLabel?: T;
              id?: T;
              blockName?: T;
            };
        cardRow?:
          | T
          | {
              sectionHeading?: T;
              sectionLayout?: T;
              sectionDescription?: T;
              sectionLinkButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        roadmap?:
          | T
          | {
              sectionHeading?: T;
              sectionLayout?: T;
              sectionDescription?: T;
              sectionLinkButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              items?:
                | T
                | {
                    time?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        scrollCards?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    showImageBorder?: T;
                    sectionLayout?: T;
                    gradient?: T;
                    gradientDirection?: T;
                    bulletPoints?: T;
                    image?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        standaloneCard?:
          | T
          | {
              title?: T;
              description?: T;
              showImageBorder?: T;
              sectionLayout?: T;
              gradient?: T;
              gradientDirection?: T;
              bulletPoints?: T;
              image?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actions_select".
 */
export interface ActionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  trigger?: T;
  functiondefinitions?: T;
  tags?: T;
  documentation?:
    | T
    | {
        label?: T;
        url?: T;
      };
  references?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  type?: T;
  location?: T;
  description?: T;
  content?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isPinned?: T;
  author?: T;
  content?: T;
  shortDescription?: T;
  heroImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  shortDescription?: T;
  about?: T;
  role?: T;
  joinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-ai-auditlog_select".
 */
export interface PayloadAiAuditlogSelect<T extends boolean = true> {
  title?: T;
  action?: T;
  targetType?: T;
  collection?: T;
  slug?: T;
  documentID?: T;
  targetURL?: T;
  additions?: T;
  removals?: T;
  before?: T;
  after?: T;
  proposal?: T;
  prompt?: T;
  inputTokens?: T;
  outputTokens?: T;
  totalTokens?: T;
  aiResponse?: T;
  userID?: T;
  userLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Optionales Navigationslogo. Wenn leer, wird das hardcoded Code0 Logo verwendet.
   */
  logo?: (number | null) | Media;
  items: {
    items: {
      title: string;
      /**
       * Leer lassen, wenn ein Submenu angezeigt werden soll.
       */
      href?: string | null;
      order: number;
      subMenu?:
        | {
            key: string;
            title: string;
            href: string;
            description: string;
            /**
             * Tabler Icon Name. Unbekannte Werte fallen auf "cube" zurück.
             */
            icon?: string | null;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[];
  };
  buttons: {
    buttons: {
      title: string;
      href: string;
      order: number;
      /**
       * Tabler Icon Name, z.B. "brand-github", oder Simple Icon mit "si", z.B. "siGithub". Leer lassen für kein Icon.
       */
      icon?: string | null;
      newTab?: boolean | null;
      variant: 'none' | 'normal' | 'outlined' | 'filled';
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  company_name: string;
  description?: string | null;
  contactEmail?: string | null;
  legalLinks: {
    privacy: {
      label: string;
      url: string;
    };
    legalNotice: {
      label: string;
      url: string;
    };
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'discord' | 'x' | 'linkedin' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  groups: {
    heading: string;
    items: {
      label: string;
      url: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner".
 */
export interface CookieBanner {
  id: number;
  common: {
    acceptAll: string;
    rejectAll: string;
    customize: string;
    save: string;
  };
  cookieBanner: {
    title: string;
    description: string;
  };
  consentManagerDialog: {
    title: string;
    description: string;
  };
  consentTypes: {
    necessary: {
      title: string;
      description: string;
    };
    measurement: {
      title: string;
      description: string;
    };
    marketing: {
      title: string;
      description: string;
    };
  };
  legalLinks: {
    privacyPolicy: {
      label: string;
      href: string;
    };
    termsOfService: {
      label: string;
      href: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionConfig".
 */
export interface SubscriptionConfig {
  id: number;
  title: string;
  pageIntro: {
    heading: string;
    description: string;
  };
  featureOverview: {
    title: string;
    description: string;
    /**
     * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
     */
    icon: string;
    id?: string | null;
  }[];
  optionsPanelHeading: string;
  deployment: {
    label: string;
    selfHosted: {
      title: string;
      description: string;
      /**
       * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
       */
      icon: string;
      color: 'brand' | 'pink' | 'yellow' | 'aqua' | 'blue';
    };
    cloud: {
      title: string;
      description: string;
      /**
       * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
       */
      icon: string;
      color: 'brand' | 'pink' | 'yellow' | 'aqua' | 'blue';
    };
  };
  customerType: {
    label: string;
    b2b: {
      title: string;
      description: string;
      /**
       * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
       */
      icon: string;
      color: 'brand' | 'pink' | 'yellow' | 'aqua' | 'blue';
    };
    b2c: {
      title: string;
      description: string;
      /**
       * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
       */
      icon: string;
      color: 'brand' | 'pink' | 'yellow' | 'aqua' | 'blue';
    };
  };
  subscriptionTier: {
    label: string;
    pro: {
      title: string;
      description: string;
      /**
       * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
       */
      icon: string;
      color: 'brand' | 'pink' | 'yellow' | 'aqua' | 'blue';
    };
    team: {
      title: string;
      description: string;
      /**
       * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
       */
      icon: string;
      color: 'brand' | 'pink' | 'yellow' | 'aqua' | 'blue';
    };
  };
  workflowExecutions: {
    title: string;
    description: string;
    min: number;
    max: number;
    step: number;
    minLabel: string;
    maxLabel: string;
    centerSuffix: string;
  };
  contactSales: {
    prompt: string;
    label: string;
    href: string;
  };
  subscribe: {
    label: string;
    baseUrl: string;
  };
  price: {
    heading: string;
    caption: string;
  };
  /**
   * Optional section heading shown above the additional features list.
   */
  additionalFeaturesLabel?: string | null;
  /**
   * Leave empty to hide the section entirely.
   */
  additionalFeatures?:
    | {
        title: string;
        description: string;
        /**
         * Tabler Icon Name ohne "Icon"-Praefix, z. B. "server", "cloud" oder "users-group". Unbekannte Werte fallen auf "cube" zurueck.
         */
        icon: string;
        /**
         * Monthly price in EUR.
         */
        price: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  items?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              href?: T;
              order?: T;
              subMenu?:
                | T
                | {
                    key?: T;
                    title?: T;
                    href?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  buttons?:
    | T
    | {
        buttons?:
          | T
          | {
              title?: T;
              href?: T;
              order?: T;
              icon?: T;
              newTab?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  company_name?: T;
  description?: T;
  contactEmail?: T;
  legalLinks?:
    | T
    | {
        privacy?:
          | T
          | {
              label?: T;
              url?: T;
            };
        legalNotice?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  groups?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner_select".
 */
export interface CookieBannerSelect<T extends boolean = true> {
  common?:
    | T
    | {
        acceptAll?: T;
        rejectAll?: T;
        customize?: T;
        save?: T;
      };
  cookieBanner?:
    | T
    | {
        title?: T;
        description?: T;
      };
  consentManagerDialog?:
    | T
    | {
        title?: T;
        description?: T;
      };
  consentTypes?:
    | T
    | {
        necessary?:
          | T
          | {
              title?: T;
              description?: T;
            };
        measurement?:
          | T
          | {
              title?: T;
              description?: T;
            };
        marketing?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  legalLinks?:
    | T
    | {
        privacyPolicy?:
          | T
          | {
              label?: T;
              href?: T;
            };
        termsOfService?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionConfig_select".
 */
export interface SubscriptionConfigSelect<T extends boolean = true> {
  title?: T;
  pageIntro?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  featureOverview?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  optionsPanelHeading?: T;
  deployment?:
    | T
    | {
        label?: T;
        selfHosted?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
            };
        cloud?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
            };
      };
  customerType?:
    | T
    | {
        label?: T;
        b2b?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
            };
        b2c?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
            };
      };
  subscriptionTier?:
    | T
    | {
        label?: T;
        pro?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
            };
        team?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
            };
      };
  workflowExecutions?:
    | T
    | {
        title?: T;
        description?: T;
        min?: T;
        max?: T;
        step?: T;
        minLabel?: T;
        maxLabel?: T;
        centerSuffix?: T;
      };
  contactSales?:
    | T
    | {
        prompt?: T;
        label?: T;
        href?: T;
      };
  subscribe?:
    | T
    | {
        label?: T;
        baseUrl?: T;
      };
  price?:
    | T
    | {
        heading?: T;
        caption?: T;
      };
  additionalFeaturesLabel?: T;
  additionalFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'pages'
      | 'features'
      | 'actions'
      | 'jobs'
      | 'blog'
      | 'team-members'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}